### ISSUE TITLE
Next release of TranscodingStreams will likely break this package

### ISSUE THREAD

**Issue by nhz2** [BioJulia/FASTX.jl#118]
https://github.com/BioJulia/FASTX.jl/blob/868d702ef8bb93c8e91f3d96507c8cfc4d7188c0/src/fasta/index.jl#L230-L234

Why does this code use the internals of `TranscodingStreams`?

I will soon remove the `transcoded` field from the `TranscodingStreams.Buffer` type, so this package will be broken.

**Comment by jakobnissen** [comment]
TranscodingStreams was originally part of BioJulia - both this package and TS were created by a collaboration between Kenta Sato and Sabrina Ward. The original authors didn't pay too much attention to public vs. private interfaces of the packages, and happily pirated between packages and reached into internals.
There has been some effort to disentangle the different packages, but it's likely lots of internals remain.

Now that I have your attention - TS provide the buffer type, but this type and its fields are not listed as part of the API. However, there is a need for a package that provide these low-level details to the user. For example, the `markpos` field, IIUC, is needed precisely for users to mark and unmark positions in the buffer, such that the user can safely read that position from the `.data` field.
It might be possible to not reach into the internals of Buffer in FASTX.jl, but the package Automa.jl is much more intimately entangled with TranscodingStreams, and needs access to its internals. Automa, in turn, is used by quite a lot of packages. I do support drawing more clear lines between public and private, but in this particular case it needs to be done carefully, lest huge parts of the ecosystem break.
