### ISSUE TITLE
Is FASTX.jl really only compatible with julia 1.1?

### ISSUE THREAD

**Issue by blaiseli** [BioJulia/FASTX.jl#12]
I'm trying to install a Julia application using FASTX in a singularity container. I had a working recipe to make this happen with a Julia 1.2 based container. Now I would like to do this in a Julia 1.0 based contained, but I got into `Unsatisfiable requirements detected for package FASTX` (see https://discourse.julialang.org/t/solving-restricted-by-julia-compatibility-requirements-to-versions-uninstalled-no-versions-left/29068).

I see that the `[compat]` section of the `Project.toml` file has precise version number indications. In particular, I see the following:
```
julia = "1.1"
```

What are the effects of these statements? This does not prevent me from using FASTX with Julia 1.2. Could this however have an effect for lower version numbers ?

**Comment by CiaranOMara** [comment]
New BioJulia packages and versions are registered in the custom [BioJuliaRegistry](https://github.com/BioJulia/BioJuliaRegistry). The feature to additionally manage custom/private registries minimally depends on Julia v1.1 (see [Pkg](https://julialang.github.io/Pkg.jl/v1/registries/)); hence the compatibility requirement.

The FASTX package is not registered in the [general registry](https://github.com/JuliaRegistries/General) that is used by Julia v1.0 and as such is not visible to Julia v1.0. FASTX features compatible with Julia v1.0 can be found in [BioSequences v1.1](https://github.com/BioJulia/BioSequences.jl/tree/v1.1.0).
