### ISSUE TITLE
Bug in `Reader` with stream

### ISSUE THREAD

**Issue by Zymergen-phaverty** [BioJulia/FASTX.jl#14]
I did

 `reader = FASTQ.Reader(GzipDecompressorStream(open(fastq)))`

 I get `UndefVarError: stream not defined`. The bug is visible in the relevant code, where `stream` is only defined inside one branch.

"""
function Reader(input::IO; fill_ambiguous = nothing)
    if fill_ambiguous === nothing
        seq_transform = nothing
    else
        seq_transform = generate_fill_ambiguous(fill_ambiguous)
    end
    if !(input isa TranscodingStream)
        stream = TranscodingStreams.NoopStream(input)
    end
    return Reader(State(stream, 1, 1, false), seq_transform)
end
"""

I think you just want 

"""
function Reader(input::IO; fill_ambiguous = nothing)
    if fill_ambiguous === nothing
        seq_transform = nothing
    else
        seq_transform = generate_fill_ambiguous(fill_ambiguous)
    end
    if !(input isa TranscodingStream)
        stream = TranscodingStreams.NoopStream(input)
    else
        stream = input
    end
    return Reader(State(stream, 1, 1, false), seq_transform)
end
"""

I'd be happy to put this in a PR if that would be helpful.

> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:. _This template is simply a tool to help everyone remember the BioJulia guidelines, if you feel anything in this template is not relevant, simply delete it._

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Package Version used:
- Julia Version used:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by phaverty** [comment]
Oops, I see that you've fixed it in master. Version bump please :-) ?

**Comment by herbstk** [comment]
I had the same issue when installing FASTX from BioJuliaRegistry.git. Looking at the installed sourcefiles confirms the repository state before #9. Using a clean install from this git repository directly works perfectly. I suppose it is a problem with BioJuliaRegistry.git?

**Comment by BenJWard** [comment]
@phaverty @herbstk Ok a bugfix version 1.1.1 is making it's way to the BioJuliaRegistry and will be released by the bots and gremlins shortly.

**Comment by phaverty** [comment]
Thanks!
