### ISSUE TITLE
Is our FASTA format idiosyncratic?

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/FASTX.jl#32]
I usually work with files where the header does not conform to the pattern `>{identifier} {description}`. For example:
`>A/New York/499/2004 |  NP | A / H3N2 | 2004-01-15 | EPI_ISL_5131`. It's clear the identifier isn't really `A/New`.

It's annoyed me for a long time that I've had to have a lot of boilerplate code like:
```
id = identifier(rec)
header = hasdescription(rec) ? id * " " * description(rec) : id
# do stuff with header
```

I also encountered that a lot in my old job with different files. Could it be just a mistake in the database I got the files from? When browsing the web, I can't actually find an (authoritative) source that states that the FASTA format has a description and the identifier separated. Instead, most of them just refer to the *header*, or *identifier*, or *description* as the whole line after `>`.

Is it possible that the idea of a separate identifier and description came from databases like Genbank, who *incidentally* began each header line with the accession number?

Considering that the current separation into identifier and description actually *destroys* information by not storing the separating whitespace, the original header can't even be reconstructed. Would it make sense to instead store the record like
```
mutable struct Record
    filled::UnitRange{Int}
    header::UnitRange{Int}
    sequence::UnitRange{Int}
    data::Vector{UInt8}
end
```
?

**Comment by jakobnissen** [comment]
After looking at the FASTA parsing, we don't actually discard any data. The header can be reconstructed using
```
function header(rec::Record)
    hasidentifier(rec) || return nothing
    id, desc = rec.identifier, rec.description
    range = first(id) : max(last(id), last(descr))
    return String(rec.data[range])
end
```
perhaps that should just be added as a function...

**Comment by BenJWard** [comment]
It's tricky because FASTA is actually pretty poorly defined. So there's scope for us to say what we think is best and consistent. Because headers and identifiers/description lines have traditionally been set or defined by say NCBI or whoever for their particular use case. But we don't throw data so there's wiggle room.

**Comment by BenJWard** [comment]
Could a future revision be to consider the separation between identifier and description to be a tab as opposed to a single space?

**Comment by jakobnissen** [comment]
You're probably right that the lack of a standard FASTA specification makes this tricky. I would probably just store the entire header line (except the leading `>`) as a header field and not discriminate between the identifier and the description. If NCBI or whoever then decides a naming scheme for fields in the header, that can be parsed out afterwards by the end user. But after realizing that no data is deleted during parsing, and now that the `header` function has been added, I have much less concern as I can simply use that function and do the parsing myself.
You can close this issue if you feel there is nothing to add here :)

**Comment by BenJWard** [comment]
Sweet, I'll consider this - at least for now - closed, as the relevant PR and desired functionality is merged.
