### ISSUE TITLE
Converting FASTQ to FASTA

### ISSUE THREAD

**Issue by jtackm** [BioJulia/FASTX.jl#50]
Hi again,

I was looking for the easiest way to convert FASTQ into FASTA (just dropping quality information). Perhaps I missed it, but there seems to be no direct conversion function (neither for whole files nor for individual records, i.e. FASTQ.Record -> FASTA.Record). The way I came up with is

```
r = FASTX.FASTQ.Reader(open("data.fastq", "r"))
w = FASTX.FASTA.Writer(open("data.fasta", "w"))
for record in r
    seq = FASTQ.sequence(record)
    id = FASTQ.identifier(record)
    record_fasta = FASTX.FASTA.Record(id, seq)
    write(w, record_fasta)
end
close(r)
close(w)
```

Which seems a bit error-prone and inconvenient compared to e.g. biopython:

```
using PyCall
SeqIO = pyimport("Bio.SeqIO")
res = SeqIO.convert("data.fastq", "fastq", "data.fasta", "fasta")
```

My questions are:
1) Does this functionality exist and I just missed it?
2) If not, is it within scope of this package and perhaps worthwhile adding?

**Comment by jakobnissen** [comment]
There is no such functionality, as far as I can tell. Yeah, it would be a worthwhile addition. Certainly a way to convert a FASTQ record to a FASTA record. Later, we can think about how to design a nice file conversion interface.

**Comment by BenJWard** [comment]
This is now possible on the master branch using the `translate(in::FASTQ.Reader, out::FASTA.Writer)` function that is exported by FASTX.
