### ISSUE TITLE
bump compatibility for BioSymbols v5 and BioSequences v3?

### ISSUE THREAD

**Issue by cecileane** [BioJulia/FASTX.jl#65]
Would it be possible to bump compatibility with BioSymbols [v5](https://github.com/BioJulia/BioSymbols.jl/releases) and BioSequences [v3](https://github.com/BioJulia/BioSequences.jl/releases)? FASTX still holds them [back](https://github.com/BioJulia/FASTX.jl/blob/master/Project.toml#L19), which prevents other packages to use later versions of BioSequences if they want to also use FASTX.
Thank you!

**Comment by jakobnissen** [comment]
Yeah, that's a good idea. I wanted to do this, but then I got sidetracked trying to tidy up the test suite of FASTX and got stuck. I'll look into it soon

**Comment by jakobnissen** [comment]
Well that was surprisingly easy. #66

**Comment by jakobnissen** [comment]
Solved in v 1.3.0.

**Comment by cecileane** [comment]
big thanks!!!
