### ISSUE TITLE
Make Documenter preview builds work.

### ISSUE THREAD

**Issue by kescobo** [BioJulia/FASTX.jl#81]
See #68

**Comment by jakobnissen** [comment]
I think the preview docs build now (I had simply forgotten to check the "write permission" for the documenter key on this guthub repo), and indeed preview docs for #84 have been built and deployed.
How do I access them, though?

**Comment by kescobo** [comment]
https://biojulia.net/FASTX.jl/previews/PR84/

And it used to be that if you click "details" on the build status on the PR, it would take you right there.

**Comment by jakobnissen** [comment]
Great - okay, looks like this can be closed as solved :)

**Comment by jakobnissen** [comment]
Nevermind, #86 just failed to build...
